server:
  #服务端口
  port: 9012
spring:
  application:
    #指定服务名
    name: tensquare-web
eureka:
  client:
    #Eureka服务的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true

# 网关的配置
zuul:
  routes:
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user